Introduce license and contact on the snap to transfer to Canonical.
canonical/charmed-openstack-exporter-snap pull request #3
Opened 2024-08-12 20:39 UTC by gabrielcocenza

[Snapcraft](https://forum.snapcraft.io/t/transfer-ownership-charmed-openstack-exporter/41374) team asked to include those fields before transferring ownership of the snap.

2024-08-12 21:18 UTC, aieri requested changes

2024-08-12 21:18 UTC, aieri commented on snap/snapcraft.yaml
> +contact: Bootstack Charmers <bootstack-charmers@lists.canonical.com>
Please use `Solutions Engineering <solutions-engineering.lists.canonical.com>`

2024-08-13 01:49 UTC, chanchiwai-ray submitted a review, later dismissed

2024-08-13 01:50 UTC, samuelallan72 submitted a review, later dismissed

2024-08-13 01:50 UTC, samuelallan72 commented on snap/snapcraft.yaml
> +contact: Solutions Engineering <solutions-engineering.lists.canonical.com>
```suggestion
contact: Solutions Engineering <solutions-engineering@lists.canonical.com>
```

I think it should be an email address?

2024-08-13 15:40 UTC, aieri approved these changes

2024-08-13 20:35 UTC, zxhdaze approved these changes

2024-08-13 20:42 UTC, merged